### ISSUE TITLE
Request for adding ISC/MIT license and publishing it to npm

### ISSUE THREAD

**Issue by webextensions** [rkristelijn/login#1]
Hi, I wish to use a sample app with basic login capabilities for running some puppeteer based tests for https://github.com/webextensions/headless-integration (it is a work-in-progress package). And I bumped into this project.

Would you be open to mark this project as ISC/MIT license?

If you find it alright, I request you to give it a unique name (or under a scoped name with your npm account) and publish it to npm for easier integration :-)

For the time being, I'll use your project linked via GitHub (awaiting appropriate license confirmation for direct usage).

**Comment by webextensions** [comment]
Also, currently, if I include in `package.json`:

```
"devDependencies": {
    "login": "github:rkristelijn/login"
}
```
and then I attempt to run `./node_modules/login/bin/www`, followed by accessing http://localhost:3000/ , then it doesn't work well. It happens so due to https://github.com/rkristelijn/login/blob/a84b73fb09df820bfbbe40df7810b6fa3b61ef59/app.js#L24 referring to `node_modules/bootstrap/...` folder which may not be available in the case I described.

Kindly add those static files into your git repository (maybe at a different path).

**Comment by rkristelijn** [comment]
First of all, thanks for your interest and usage of my repo. The reason I put this here so other people can benefit from it, so per request I flagged the desired license.

As for your other query, the reason I would like to keep it in the node_modules folder is, so that it can be updated via npm, likewise is flagged whenever a security issue is discovered in the package. My proposed fix is to check for `node_modules` in `__dirname()`. if it does exist, change the path to include bootstrap.

I've tested with your project, but the test `should load the login access page properly` still fails. However I'm now able to see the bootstrap style in the screenshot and run `./node_modules/login/bin/www` also works fine now. 

I've created a npm package and created a [PR](https://github.com/webextensions/headless-integration/pull/2) Please let me know if I can be of more help.

**Comment by webextensions** [comment]
@rkristelijn 
Thanks for the changes :-)

Since the approach of checking for `node_modules` in `__dirname` may fail in certain scenarios (described in the PR https://github.com/rkristelijn/login/pull/2).

I am hoping that you may reconsider the approach since the suggested change solves the main concerns of simpler updates.

**Comment by rkristelijn** [comment]
@webextensions 
Thanks for the PR. Didn't think about this approach

Please update to login-expres-login v1.1.0 and close the issue

**Comment by webextensions** [comment]
Marking closed.

There is an issue in my PR https://github.com/rkristelijn/login/pull/2 (that `postinstall` script gets executed even when this package is being used as a sub-package).

For the time being, I avoid that by running `npm install --ignore-scripts`.

I'll raise another PR to fix that.
